jobs:

- job: Windows

  pool:
    vmImage: 'windows-latest'

  variables:
    - name: NUGET_PACKAGES
      value: $(Agent.WorkFolder)\.nuget
    - name: NUGET_HTTP_CACHE_PATH
      value: $(Agent.WorkFolder)\.nuget-http-cache
    - group: 'Uno Platform authenticode signing'

  steps:
  - checkout: self
    clean: true

  - template: gitversion-step.yml

  - task: UseDotNet@2
    displayName: 'Use .NET 5 SDK'
    inputs:
      version: 5.x

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      version: 8.0.100
      includePreviewVersions: true

  - powershell: |
      dotnet build /r /p:Configuration=Release src/SQLitePCLRaw.Wasm-ci.slnf "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=$env:GITVERSION_FullSemVer" "/p:InformationalVersion=$env:GITVERSION_InformationalVersion" /detailedsummary

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.504'

  - task: PowerShell@2
    displayName: Authenticode Sign Packages
    inputs:
      filePath: build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      SignPackageName: "Uno.SQLitePCLRaw.Wasm"
      SignPackageDescription: "Uno.SQLitePCLRaw.Wasm"
      ArtifactDirectory: $(build.artifactstagingdirectory)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: uno.sqlitepclwasmprovider-drop
      publishLocation: Container

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  container: unoplatform/wasm-build:3.0

  variables:
    DotnetRuntimePath: /usr/share/dotnet

  steps:
  - checkout: self
    clean: true

  - template: gitversion-step.yml

  - task: UseDotNet@2
    displayName: 'Use .NET 5 SDK'
    inputs:
      version: 5.x

  - task: UseDotNet@2
    displayName: 'Use .NET SDK'
    inputs:
      version: 9.0.100-rc.2.24474.11
      includePreviewVersions: true

  - bash: |
      dotnet publish -c Release "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=$GITVERSION_FULLSEMVER" "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" ./src/samples/EFCoreSample/EFCoreSample.Wasm/EFCoreSample.Wasm.csproj

    displayName: 'Build Wasm Head'

  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: ./src/samples/EFCoreSample/EFCoreSample.Wasm/bin/Release/net9.0/publish/wwwroot
      artifactType: container
      artifactName: EFCoreSample-Wasm